<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

require_once __DIR__ . '/../../../vendor/autoload.php';


class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {//die('here');
        // replace this example code with whatever you need
        //return $this->render('default/index.html.twig', [
         //   'base_dir' => realpath($this->getParameter('kernel.project_dir')).DIRECTORY_SEPARATOR,
        //]);
		
		// This file is generated by Composer

		$client = new \Github\Client();
		//echo '<pre>';print_r($client);exit;
		
		$repositories = $client->api('user')->repositories('ornicar');
		//echo '<pre>';print_r($repositories);exit;

		 return $this->render('default/index.html.twig', array("repositories" => $repositories));
		
    }
}
